export const CHANGE_PAGE = "CHANGE_PAGE";
export const GET_CONFIG = "GET_CONFIG";
export const CHANGE_ADMIN_SEARCH_INPUT = "CHANGE_ADMIN_SEARCH_INPUT";
export const USER_LIST_SUCCESS_FETCH = "USER_LIST_FETCH";
export const USER_LIST_HAS_ERRORED = "USER_LIST_HAS_ERRORED";
export const USER_LIST_IS_LOADING = "USER_LIST_IS_LOADING";
export const CHANGE_CURRENT_USER = "CHANGE_CURRENT_USER";
export const CREATE_CURRENT_USER = "CREATE_CURRENT_USER";
